export const effects = [
  { name: "Android", isDisabled: false },
  { name: "Breath", isDisabled: false },
  { name: "Candle", isDisabled: false },
  { name: "Christmas", isDisabled: false },
  { name: "Dissolve", isDisabled: false },
  { name: "Fade", isDisabled: false },
  { name: "Fire", isDisabled: true },
  { name: "Flow", isDisabled: true },
  { name: "Glitter", isDisabled: true },
  { name: "Lake", isDisabled: true },
  { name: "Palette", isDisabled: true },
  { name: "Police", isDisabled: true },
  { name: "Rainbow", isDisabled: true },
  { name: "Ripple", isDisabled: true },
  { name: "Scan", isDisabled: true },
  { name: "Sunrise", isDisabled: true },
  { name: "Theater", isDisabled: true },
  { name: "Wipe", isDisabled: true },
];
